"""
XNRA Element Spectra Module
============================
Parsing and visualization of SIMNRA element spectrum export files.

This module handles:
- Parsing element spectrum .txt files exported from SIMNRA
- Separating element totals from isotope-specific contributions
- Plotting element/isotope spectra with interactive hover
- Calculating element counts for uncertainty analysis

Usage:
------
    from xnra_element_spectra import (
        parse_element_spectrum,
        plot_element_spectra,
        get_element_spectrum_summary,
    )
    
    # Parse file
    data = parse_element_spectrum("spectrum.txt")
    
    # Plot
    plot_element_spectra(data, elements_to_plot=['Si', 'O', 'Ca'])

Authors: Berke Santos & Giuseppe Legrottaglie
Version: 1.0 (extracted from xnra_uncertainty_v9)
"""

import numpy as np
from pathlib import Path
from typing import Dict, List, Tuple, Optional


# Default colors for element spectrum plotting (expanded palette - 30 colors)
ELEMENT_COLORS = [
    # Primary colors (distinct)
    '#1f77b4',  # blue
    '#ff7f0e',  # orange
    '#2ca02c',  # green
    '#d62728',  # red
    '#9467bd',  # purple
    '#8c564b',  # brown
    '#e377c2',  # pink
    '#17becf',  # cyan
    '#bcbd22',  # olive
    '#7f7f7f',  # gray
    # Secondary colors (variations)
    '#aec7e8',  # light blue
    '#ffbb78',  # light orange
    '#98df8a',  # light green
    '#ff9896',  # light red
    '#c5b0d5',  # light purple
    '#c49c94',  # light brown
    '#f7b6d2',  # light pink
    '#9edae5',  # light cyan
    '#dbdb8d',  # light olive
    '#c7c7c7',  # light gray
    # Tertiary colors (more variations)
    '#393b79',  # dark blue
    '#e6550d',  # dark orange
    '#31a354',  # dark green
    '#ad494a',  # dark red
    '#756bb1',  # dark purple
    '#636363',  # dark gray
    '#6b6ecf',  # indigo
    '#b5cf6b',  # lime
    '#ce6dbd',  # magenta
    '#de9ed6',  # orchid
]

# Map hex colors to readable names
COLOR_NAMES = {
    '#1f77b4': 'blue',
    '#ff7f0e': 'orange',
    '#2ca02c': 'green',
    '#d62728': 'red',
    '#9467bd': 'purple',
    '#8c564b': 'brown',
    '#e377c2': 'pink',
    '#17becf': 'cyan',
    '#bcbd22': 'olive',
    '#7f7f7f': 'gray',
    '#aec7e8': 'light blue',
    '#ffbb78': 'light orange',
    '#98df8a': 'light green',
    '#ff9896': 'light red',
    '#c5b0d5': 'light purple',
    '#c49c94': 'light brown',
    '#f7b6d2': 'light pink',
    '#9edae5': 'light cyan',
    '#dbdb8d': 'light olive',
    '#c7c7c7': 'light gray',
    '#393b79': 'dark blue',
    '#e6550d': 'dark orange',
    '#31a354': 'dark green',
    '#ad494a': 'dark red',
    '#756bb1': 'dark purple',
    '#636363': 'dark gray',
    '#6b6ecf': 'indigo',
    '#b5cf6b': 'lime',
    '#ce6dbd': 'magenta',
    '#de9ed6': 'orchid',
    'black': 'black',
    '#000000': 'black',
}


def parse_element_spectrum(filepath: str, keep_isotopes: bool = True) -> Dict:
    """
    Parse SIMNRA element spectrum export file.
    
    This file is generated by SIMNRA via:
    Plot → Show Element Spectra (enable)
    File → Write Spectrum Data
    
    Format: Tab-separated columns with header row containing element names.
    First column is channel number, subsequent columns are element contributions.
    
    Parameters
    ----------
    filepath : str
        Path to the element spectrum .txt file
    keep_isotopes : bool, default=True
        If True, preserve isotope-specific spectra separately.
        If False, merge isotopes into parent elements (v8 behavior).
    
    Returns
    -------
    dict
        Dictionary containing:
        - channels: np.array of channel numbers
        - elements: list of element names (from header)
        - isotopes: list of isotope names (e.g., '12C', '16O')
        - element_spectra: dict mapping element name → np.array of counts
        - isotope_spectra: dict mapping isotope name → np.array of counts
        - total_simulated: np.array of summed simulated counts
        - isotope_to_element: dict mapping isotope → parent element
    """
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    if not lines:
        raise ValueError(f"Empty file: {filepath}")
    
    # Parse header line
    header = lines[0].strip().split('\t')
    
    # First column is 'channel', rest are element/isotope names
    if header[0].lower() != 'channel':
        raise ValueError(f"Expected 'channel' as first column, got: {header[0]}")
    
    column_names = header[1:]

    # Reserved column names that SIMNRA exports alongside element columns.
    # These are spectra in their own right, NOT elements/isotopes, and must
    # not appear in the elements list.
    RESERVED = {'experimental', 'smoothed', 'simulated', 'fit', 'total',
                'calculated', 'sum', 'residual', 'background'}

    # Categorize columns as elements, isotopes, or special (reserved) spectra
    elements = []  # Pure element symbols (no mass number)
    isotopes = []  # Isotopes with mass numbers (e.g., '12C', '16O')
    isotope_to_element = {}  # Map isotope → parent element
    element_column_indices = {}  # element → column index
    isotope_column_indices = {}  # isotope → column index
    special_column_indices = {}  # special spectrum name → column index

    for i, name in enumerate(column_names):
        if not name:
            continue

        if name.lower() in RESERVED:
            # SIMNRA-exported reference spectrum (experimental / smoothed /
            # simulated / fit / ...). Keep data but exclude from element list.
            special_column_indices[name] = i
        elif name[0].isalpha():
            # Element total (e.g., 'C', 'O', 'Si')
            elements.append(name)
            element_column_indices[name] = i
        else:
            # Isotope (e.g., '12C', '16O')
            isotopes.append(name)
            isotope_column_indices[name] = i
            parent = ''.join(c for c in name if c.isalpha())
            isotope_to_element[name] = parent
    
    # Parse data lines
    channels = []
    data_columns = {name: [] for name in column_names}
    
    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue
        
        parts = line.split('\t')
        if len(parts) < 2:
            continue
        
        try:
            channel = int(parts[0])
            channels.append(channel)
            
            for i, name in enumerate(column_names):
                if i + 1 < len(parts):
                    # Parse scientific notation (e.g., 1.23E+0004)
                    val = float(parts[i + 1])
                else:
                    val = 0.0
                data_columns[name].append(val)
        except (ValueError, IndexError):
            continue
    
    channels = np.array(channels)

    # Convert to numpy arrays - separate element, isotope, and special spectra
    element_spectra = {}
    isotope_spectra = {}
    special_spectra = {}  # e.g., 'Experimental', 'Smoothed', 'Simulated'

    for name in column_names:
        if name not in data_columns:
            continue
        arr = np.array(data_columns[name])
        if name in element_column_indices:
            element_spectra[name] = arr
        elif name in isotope_column_indices:
            isotope_spectra[name] = arr
        elif name in special_column_indices:
            special_spectra[name] = arr

    # Calculate total simulated (sum of element contributions only, to avoid double counting)
    total_simulated = np.zeros(len(channels))
    for elem in elements:
        if elem in element_spectra:
            total_simulated += element_spectra[elem]

    return {
        'filepath': str(filepath),
        'channels': channels,
        'elements': elements,
        'isotopes': isotopes,
        'all_columns': column_names,
        'element_spectra': element_spectra,
        'isotope_spectra': isotope_spectra,
        'special_spectra': special_spectra,
        'total_simulated': total_simulated,
        'isotope_to_element': isotope_to_element,
        'element_column_indices': element_column_indices,
        'isotope_column_indices': isotope_column_indices,
        'special_column_indices': special_column_indices,
    }


def get_available_elements(element_spectrum_data: Dict) -> List[str]:
    """Get list of elements available in the element spectrum file."""
    return element_spectrum_data.get('elements', [])


def get_available_isotopes(element_spectrum_data: Dict) -> List[str]:
    """Get list of isotopes available in the element spectrum file."""
    return element_spectrum_data.get('isotopes', [])


def get_element_spectrum_summary(element_spectrum_data: Dict) -> Dict:
    """
    Get a summary of the element spectrum data for display.
    
    Returns
    -------
    dict
        Summary with element/isotope names, total counts, channel range, etc.
    """
    if not element_spectrum_data:
        return {}
    
    channels = element_spectrum_data.get('channels', np.array([]))
    elements = element_spectrum_data.get('elements', [])
    isotopes = element_spectrum_data.get('isotopes', [])
    element_spectra = element_spectrum_data.get('element_spectra', {})
    isotope_spectra = element_spectrum_data.get('isotope_spectra', {})
    isotope_to_element = element_spectrum_data.get('isotope_to_element', {})
    
    # Calculate total counts per element
    element_totals = {}
    for elem in elements:
        if elem in element_spectra:
            element_totals[elem] = int(np.sum(element_spectra[elem]))
    
    # Calculate total counts per isotope
    isotope_totals = {}
    for iso in isotopes:
        if iso in isotope_spectra:
            isotope_totals[iso] = int(np.sum(isotope_spectra[iso]))
    
    return {
        'filepath': element_spectrum_data.get('filepath', ''),
        'channel_min': int(channels.min()) if len(channels) > 0 else 0,
        'channel_max': int(channels.max()) if len(channels) > 0 else 0,
        'n_channels': len(channels),
        'elements': elements,
        'isotopes': isotopes,
        'element_totals': element_totals,
        'isotope_totals': isotope_totals,
        'isotope_to_element': isotope_to_element,
    }


def calculate_element_counts_from_spectrum(
    element_spectrum_data: Dict,
    experimental_counts: np.ndarray,
    element_or_isotope: str,
    roi_start: int,
    roi_end: int,
    use_isotope: bool = False
) -> Tuple[int, float, float]:
    """
    Calculate element/isotope counts directly from the simulated spectrum.

    A_A is taken as the integrated simulated counts for the element/isotope
    in the ROI — no experimental normalization is applied. The statistical
    uncertainty ΔA_A = 1/√A_A therefore reflects the *predicted* counting
    statistics, not the measured ones.

    Formula:
        A_A = Σ(sim_A[ROI])

    The element fraction f_A = Σ(sim_A[ROI]) / Σ(sim_total[ROI]) and the
    experimental ROI sum are still returned as diagnostics.

    Parameters
    ----------
    element_spectrum_data : dict
        Output from parse_element_spectrum()
    experimental_counts : np.ndarray
        Experimental spectrum from .xnra file. Used only for the diagnostic
        return value; does NOT enter the A_A calculation.
    element_or_isotope : str
        Element symbol (e.g., 'Si', 'O', 'Ca') or isotope (e.g., '12C', '16O')
    roi_start : int
        Start channel of ROI (inclusive)
    roi_end : int
        End channel of ROI (inclusive)
    use_isotope : bool, default=False
        If True, look for isotope-specific spectrum; if False, use element total

    Returns
    -------
    tuple
        (element_counts, element_fraction, total_exp_counts)
        - element_counts: Σ(sim_A[ROI]) — integrated simulated counts (A_A)
        - element_fraction: f_A = Σ(sim_A[ROI]) / Σ(sim_total[ROI]) (diagnostic)
        - total_exp_counts: Σ(exp[ROI]) — experimental ROI sum (diagnostic)
    """
    channels = element_spectrum_data['channels']

    # Map ROI to array indices
    roi_mask = (channels >= roi_start) & (channels <= roi_end)

    if not np.any(roi_mask):
        return 0, 0.0, 0

    # Choose spectrum source based on whether we want isotope-specific data
    if use_isotope and element_or_isotope in element_spectrum_data.get('isotope_spectra', {}):
        sim_spectrum = element_spectrum_data['isotope_spectra'][element_or_isotope]
    elif element_or_isotope in element_spectrum_data.get('element_spectra', {}):
        sim_spectrum = element_spectrum_data['element_spectra'][element_or_isotope]
    else:
        # Try case-insensitive match
        for key, spectrum in element_spectrum_data.get('element_spectra', {}).items():
            if key.lower() == element_or_isotope.lower():
                sim_spectrum = spectrum
                break
        else:
            for key, spectrum in element_spectrum_data.get('isotope_spectra', {}).items():
                if key.lower() == element_or_isotope.lower():
                    sim_spectrum = spectrum
                    break
            else:
                return 0, 0.0, 0

    total_simulated = element_spectrum_data['total_simulated']

    # Sum in ROI
    sim_element_roi = float(np.sum(sim_spectrum[roi_mask]))
    sim_total_roi = float(np.sum(total_simulated[roi_mask]))

    # Element fraction (kept as diagnostic)
    if sim_total_roi > 0:
        element_fraction = sim_element_roi / sim_total_roi
    else:
        element_fraction = 0.0

    # Experimental ROI sum — diagnostic only, no longer used for A_A
    total_exp_counts = 0
    if experimental_counts is not None:
        exp_roi_start = max(0, roi_start)
        exp_roi_end = min(len(experimental_counts), roi_end + 1)
        if exp_roi_start < exp_roi_end:
            total_exp_counts = int(np.sum(experimental_counts[exp_roi_start:exp_roi_end]))

    # A_A = simulated element counts in ROI (direct, no experimental normalization)
    element_counts = int(round(sim_element_roi))

    return element_counts, element_fraction, total_exp_counts


def plot_element_spectra(element_spectrum_data: Dict,
                         elements_to_plot: List[str] = None,
                         isotopes_to_plot: List[str] = None,
                         show_simulated: bool = False,
                         show_raw: bool = False,
                         show_smoothed: bool = False,
                         figure_size: Tuple[float, float] = (12, 6),
                         dpi: int = 100,
                         title: str = None,
                         x_axis_mode: str = 'channel',
                         cal_offset: float = 0,
                         cal_gain: float = 1,
                         line_width: float = 1.5,
                         show_legend: bool = True,
                         show_plot: bool = True,
                         channel_min: Optional[float] = None,
                         channel_max: Optional[float] = None,
                         energy_min: Optional[float] = None,
                         energy_max: Optional[float] = None,
                         counts_min: Optional[float] = None,
                         counts_max: Optional[float] = None):
    """
    Plot element and/or isotope spectra from a SIMNRA element-spectrum file.

    Interactive hover is enabled when mplcursors is available.

    Overlays (when present in the file under reserved column names
    'Simulated' / 'Experimental' or 'Raw' / 'Smoothed') can be shown on top
    of the element/isotope curves via the show_* flags.

    Parameters
    ----------
    element_spectrum_data : dict
        Output of parse_element_spectrum().
    elements_to_plot, isotopes_to_plot : list, optional
        Which element/isotope curves to draw. If both are None, all elements
        are plotted.
    show_simulated, show_raw, show_smoothed : bool
        Overlay the reserved spectra from the file (if present).
    x_axis_mode : {'channel', 'energy'}
    cal_offset, cal_gain : float
        Energy calibration (E = offset + gain·channel). Only used to compute
        the x-axis in energy mode; NOT displayed on the plot.
    channel_min, channel_max, energy_min, energy_max, counts_min, counts_max : float, optional
        Axis limits. The channel/energy pair used depends on x_axis_mode.
    """
    import matplotlib.pyplot as plt
    from matplotlib.ticker import FormatStrFormatter

    channels = element_spectrum_data['channels']
    element_spectra = element_spectrum_data.get('element_spectra', {})
    isotope_spectra = element_spectrum_data.get('isotope_spectra', {})
    special_spectra = element_spectrum_data.get('special_spectra', {})

    # Resolve defaults for selection
    if elements_to_plot is None and isotopes_to_plot is None:
        elements_to_plot = element_spectrum_data.get('elements', [])
    if elements_to_plot is None:
        elements_to_plot = []
    if isotopes_to_plot is None:
        isotopes_to_plot = []

    fig, ax = plt.subplots(figsize=figure_size, dpi=dpi)

    # X-axis values
    if x_axis_mode.lower() == 'energy':
        x_values = cal_offset + cal_gain * channels
        x_label = 'Energy [keV]'
    else:
        x_values = channels
        x_label = 'Channel'

    color_idx = 0
    lines = []
    line_labels = []

    # ---- Overlays from the SIMNRA file (reserved columns) ----
    # Case-insensitive lookup helper
    def _find_special(*candidates):
        keys = {k.lower(): k for k in special_spectra.keys()}
        for c in candidates:
            if c.lower() in keys:
                return keys[c.lower()], special_spectra[keys[c.lower()]]
        return None, None

    if show_simulated:
        key, arr = _find_special('Simulated', 'Calculated', 'Fit', 'Total')
        if arr is not None:
            line, = ax.plot(x_values, arr, color='black', linestyle='--',
                            linewidth=line_width * 0.9, label=key,
                            alpha=0.7, zorder=1)
            lines.append(line); line_labels.append(key)

    if show_raw:
        key, arr = _find_special('Experimental', 'Raw')
        if arr is not None:
            line, = ax.plot(x_values, arr, color='dimgray', linewidth=line_width * 0.8,
                            alpha=0.6, label=key, zorder=1)
            lines.append(line); line_labels.append(key)

    if show_smoothed:
        key, arr = _find_special('Smoothed')
        if arr is not None:
            line, = ax.plot(x_values, arr, color='saddlebrown',
                            linestyle=':', linewidth=line_width * 0.9,
                            alpha=0.7, label=key, zorder=1)
            lines.append(line); line_labels.append(key)

    # ---- Element curves ----
    for elem in elements_to_plot:
        if elem in element_spectra:
            color = ELEMENT_COLORS[color_idx % len(ELEMENT_COLORS)]
            line, = ax.plot(x_values, element_spectra[elem],
                            color=color, linewidth=line_width,
                            label=elem, zorder=2)
            lines.append(line); line_labels.append(elem)
            color_idx += 1

    # ---- Isotope curves ----
    for iso in isotopes_to_plot:
        if iso in isotope_spectra:
            color = ELEMENT_COLORS[color_idx % len(ELEMENT_COLORS)]
            line, = ax.plot(x_values, isotope_spectra[iso],
                            color=color, linewidth=line_width,
                            label=iso, linestyle='-.', zorder=2)
            lines.append(line); line_labels.append(iso)
            color_idx += 1

    # Labels and title
    ax.set_xlabel(x_label, fontsize=12, fontweight='bold')
    ax.set_ylabel('Counts', fontsize=12, fontweight='bold')
    ax.set_title(title if title else 'Element Spectra',
                 fontsize=14, fontweight='bold')

    # 2-decimal tick formatting on both axes
    ax.xaxis.set_major_formatter(FormatStrFormatter('%.2f'))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.2f'))

    # Axis limits
    if x_axis_mode.lower() == 'energy':
        if energy_min is not None or energy_max is not None:
            ax.set_xlim(left=energy_min, right=energy_max)
    else:
        if channel_min is not None or channel_max is not None:
            ax.set_xlim(left=channel_min, right=channel_max)
    if counts_min is not None or counts_max is not None:
        ax.set_ylim(bottom=counts_min, top=counts_max)

    if show_legend and (elements_to_plot or isotopes_to_plot
                        or show_simulated or show_raw or show_smoothed):
        ax.legend(loc='upper right', fontsize=9, framealpha=0.9)

    ax.grid(True, alpha=0.3, linestyle='--')

    try:
        import mplcursors
        cursor = mplcursors.cursor(lines, hover=2)

        @cursor.connect("add")
        def on_add(sel):
            line = sel.artist
            if line not in lines:
                return
            idx = lines.index(line)
            label = line_labels[idx]
            color = line.get_color()
            x_val, y_val = sel.target[0], sel.target[1]
            unit = 'keV' if x_axis_mode.lower() == 'energy' else 'Ch'
            color_name = COLOR_NAMES.get(color, color)
            text = f"{label} ({color_name})\n{x_val:.2f} {unit} | {y_val:.2f} cts"
            sel.annotation.set_text(text)
            sel.annotation.set_fontsize(10)
            sel.annotation.set_fontweight('bold')
            sel.annotation.set_color(color)
            sel.annotation.get_bbox_patch().set_facecolor('white')
            sel.annotation.get_bbox_patch().set_alpha(0.95)
            sel.annotation.get_bbox_patch().set_edgecolor(color)
            sel.annotation.get_bbox_patch().set_linewidth(2)

        print("✓ Interactive hover enabled (mplcursors)")
    except ImportError:
        print("ℹ️  For interactive hover, install mplcursors: pip install mplcursors")

    plt.tight_layout()
    if show_plot:
        plt.show()
    return fig


def main():
    """Simple CLI for testing."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Plot SIMNRA element spectra')
    parser.add_argument('input', help='Element spectrum .txt file')
    parser.add_argument('-e', '--elements', help='Comma-separated elements to plot')
    parser.add_argument('-i', '--isotopes', help='Comma-separated isotopes to plot')
    parser.add_argument('--show-simulated', action='store_true', help='Overlay Simulated column from file')
    parser.add_argument('--show-raw', action='store_true', help='Overlay Experimental/Raw column from file')
    parser.add_argument('--show-smoothed', action='store_true', help='Overlay Smoothed column from file')
    parser.add_argument('--energy', action='store_true', help='Use energy x-axis')
    parser.add_argument('--offset', type=float, default=0, help='Calibration offset')
    parser.add_argument('--gain', type=float, default=1, help='Calibration gain')
    parser.add_argument('-t', '--title', help='Plot title')
    
    args = parser.parse_args()
    
    # Parse file
    data = parse_element_spectrum(args.input)
    summary = get_element_spectrum_summary(data)
    
    print(f"\nLoaded: {args.input}")
    print(f"Channels: {summary['channel_min']} - {summary['channel_max']} ({summary['n_channels']} points)")
    print(f"Elements: {', '.join(summary['elements'])}")
    print(f"Isotopes: {', '.join(summary['isotopes'])}")
    
    # Determine what to plot
    elements = None
    isotopes = None
    
    if args.elements:
        elements = [e.strip() for e in args.elements.split(',')]
    if args.isotopes:
        isotopes = [i.strip() for i in args.isotopes.split(',')]
    
    # Plot
    plot_element_spectra(
        data,
        elements_to_plot=elements,
        isotopes_to_plot=isotopes,
        show_simulated=args.show_simulated,
        show_raw=args.show_raw,
        show_smoothed=args.show_smoothed,
        x_axis_mode='energy' if args.energy else 'channel',
        cal_offset=args.offset,
        cal_gain=args.gain,
        title=args.title,
    )


if __name__ == '__main__':
    main()
