"""
XNRA Element Spectra Module
============================
Parsing and visualization of SIMNRA element spectrum export files.

This module handles:
- Parsing element spectrum .txt files exported from SIMNRA
- Separating element totals from isotope-specific contributions
- Plotting element/isotope spectra with interactive hover
- Calculating element counts for uncertainty analysis

Usage:
------
    from xnra_element_spectra import (
        parse_element_spectrum,
        plot_element_spectra,
        get_element_spectrum_summary,
    )
    
    # Parse file
    data = parse_element_spectrum("spectrum.txt")
    
    # Plot
    plot_element_spectra(data, elements_to_plot=['Si', 'O', 'Ca'])

Authors: Berke Santos & Giuseppe Legrottaglie
Version: 1.0 (extracted from xnra_uncertainty_v9)
"""

import numpy as np
from pathlib import Path
from typing import Dict, List, Tuple, Optional


# =============================================================================
# COLOR DEFINITIONS
# =============================================================================

# Default colors for element spectrum plotting (expanded palette - 30 colors)
ELEMENT_COLORS = [
    # Primary colors (distinct)
    '#1f77b4',  # blue
    '#ff7f0e',  # orange
    '#2ca02c',  # green
    '#d62728',  # red
    '#9467bd',  # purple
    '#8c564b',  # brown
    '#e377c2',  # pink
    '#17becf',  # cyan
    '#bcbd22',  # olive
    '#7f7f7f',  # gray
    # Secondary colors (variations)
    '#aec7e8',  # light blue
    '#ffbb78',  # light orange
    '#98df8a',  # light green
    '#ff9896',  # light red
    '#c5b0d5',  # light purple
    '#c49c94',  # light brown
    '#f7b6d2',  # light pink
    '#9edae5',  # light cyan
    '#dbdb8d',  # light olive
    '#c7c7c7',  # light gray
    # Tertiary colors (more variations)
    '#393b79',  # dark blue
    '#e6550d',  # dark orange
    '#31a354',  # dark green
    '#ad494a',  # dark red
    '#756bb1',  # dark purple
    '#636363',  # dark gray
    '#6b6ecf',  # indigo
    '#b5cf6b',  # lime
    '#ce6dbd',  # magenta
    '#de9ed6',  # orchid
]

# Map hex colors to readable names
COLOR_NAMES = {
    '#1f77b4': 'blue',
    '#ff7f0e': 'orange',
    '#2ca02c': 'green',
    '#d62728': 'red',
    '#9467bd': 'purple',
    '#8c564b': 'brown',
    '#e377c2': 'pink',
    '#17becf': 'cyan',
    '#bcbd22': 'olive',
    '#7f7f7f': 'gray',
    '#aec7e8': 'light blue',
    '#ffbb78': 'light orange',
    '#98df8a': 'light green',
    '#ff9896': 'light red',
    '#c5b0d5': 'light purple',
    '#c49c94': 'light brown',
    '#f7b6d2': 'light pink',
    '#9edae5': 'light cyan',
    '#dbdb8d': 'light olive',
    '#c7c7c7': 'light gray',
    '#393b79': 'dark blue',
    '#e6550d': 'dark orange',
    '#31a354': 'dark green',
    '#ad494a': 'dark red',
    '#756bb1': 'dark purple',
    '#636363': 'dark gray',
    '#6b6ecf': 'indigo',
    '#b5cf6b': 'lime',
    '#ce6dbd': 'magenta',
    '#de9ed6': 'orchid',
    'black': 'black',
    '#000000': 'black',
}


# =============================================================================
# PARSING FUNCTIONS
# =============================================================================

def parse_element_spectrum(filepath: str, keep_isotopes: bool = True) -> Dict:
    """
    Parse SIMNRA element spectrum export file.
    
    This file is generated by SIMNRA via:
    Plot → Show Element Spectra (enable)
    File → Write Spectrum Data
    
    Format: Tab-separated columns with header row containing element names.
    First column is channel number, subsequent columns are element contributions.
    
    Parameters
    ----------
    filepath : str
        Path to the element spectrum .txt file
    keep_isotopes : bool, default=True
        If True, preserve isotope-specific spectra separately.
        If False, merge isotopes into parent elements (v8 behavior).
    
    Returns
    -------
    dict
        Dictionary containing:
        - channels: np.array of channel numbers
        - elements: list of element names (from header)
        - isotopes: list of isotope names (e.g., '12C', '16O')
        - element_spectra: dict mapping element name → np.array of counts
        - isotope_spectra: dict mapping isotope name → np.array of counts
        - total_simulated: np.array of summed simulated counts
        - isotope_to_element: dict mapping isotope → parent element
    """
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    if not lines:
        raise ValueError(f"Empty file: {filepath}")
    
    # Parse header line
    header = lines[0].strip().split('\t')
    
    # First column is 'channel', rest are element/isotope names
    if header[0].lower() != 'channel':
        raise ValueError(f"Expected 'channel' as first column, got: {header[0]}")
    
    column_names = header[1:]
    
    # Categorize columns as elements vs isotopes
    elements = []  # Pure element symbols (no mass number)
    isotopes = []  # Isotopes with mass numbers (e.g., '12C', '16O')
    isotope_to_element = {}  # Map isotope → parent element
    element_column_indices = {}  # element → list of column indices
    isotope_column_indices = {}  # isotope → column index
    
    for i, name in enumerate(column_names):
        if not name:
            continue
        
        # Check if it's an isotope (starts with number) or element (letter only)
        if name[0].isalpha():
            # This is an element total (e.g., 'C', 'O', 'Si')
            elements.append(name)
            element_column_indices[name] = i
        else:
            # This is an isotope (e.g., '12C', '16O')
            isotopes.append(name)
            isotope_column_indices[name] = i
            
            # Find parent element
            parent = ''.join(c for c in name if c.isalpha())
            isotope_to_element[name] = parent
    
    # Parse data lines
    channels = []
    data_columns = {name: [] for name in column_names}
    
    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue
        
        parts = line.split('\t')
        if len(parts) < 2:
            continue
        
        try:
            channel = int(parts[0])
            channels.append(channel)
            
            for i, name in enumerate(column_names):
                if i + 1 < len(parts):
                    # Parse scientific notation (e.g., 1.23E+0004)
                    val = float(parts[i + 1])
                else:
                    val = 0.0
                data_columns[name].append(val)
        except (ValueError, IndexError):
            continue
    
    channels = np.array(channels)
    
    # Convert to numpy arrays - separate element and isotope spectra
    element_spectra = {}
    isotope_spectra = {}
    
    for name in column_names:
        arr = np.array(data_columns[name])
        if name in element_column_indices:
            element_spectra[name] = arr
        elif name in isotope_column_indices:
            isotope_spectra[name] = arr
    
    # Calculate total simulated (sum of element contributions only, to avoid double counting)
    total_simulated = np.zeros(len(channels))
    for elem in elements:
        if elem in element_spectra:
            total_simulated += element_spectra[elem]
    
    return {
        'filepath': str(filepath),
        'channels': channels,
        'elements': elements,
        'isotopes': isotopes,
        'all_columns': column_names,
        'element_spectra': element_spectra,
        'isotope_spectra': isotope_spectra,
        'total_simulated': total_simulated,
        'isotope_to_element': isotope_to_element,
        'element_column_indices': element_column_indices,
        'isotope_column_indices': isotope_column_indices,
    }


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_available_elements(element_spectrum_data: Dict) -> List[str]:
    """Get list of elements available in the element spectrum file."""
    return element_spectrum_data.get('elements', [])


def get_available_isotopes(element_spectrum_data: Dict) -> List[str]:
    """Get list of isotopes available in the element spectrum file."""
    return element_spectrum_data.get('isotopes', [])


def get_element_spectrum_summary(element_spectrum_data: Dict) -> Dict:
    """
    Get a summary of the element spectrum data for display.
    
    Returns
    -------
    dict
        Summary with element/isotope names, total counts, channel range, etc.
    """
    if not element_spectrum_data:
        return {}
    
    channels = element_spectrum_data.get('channels', np.array([]))
    elements = element_spectrum_data.get('elements', [])
    isotopes = element_spectrum_data.get('isotopes', [])
    element_spectra = element_spectrum_data.get('element_spectra', {})
    isotope_spectra = element_spectrum_data.get('isotope_spectra', {})
    isotope_to_element = element_spectrum_data.get('isotope_to_element', {})
    
    # Calculate total counts per element
    element_totals = {}
    for elem in elements:
        if elem in element_spectra:
            element_totals[elem] = int(np.sum(element_spectra[elem]))
    
    # Calculate total counts per isotope
    isotope_totals = {}
    for iso in isotopes:
        if iso in isotope_spectra:
            isotope_totals[iso] = int(np.sum(isotope_spectra[iso]))
    
    return {
        'filepath': element_spectrum_data.get('filepath', ''),
        'channel_min': int(channels.min()) if len(channels) > 0 else 0,
        'channel_max': int(channels.max()) if len(channels) > 0 else 0,
        'n_channels': len(channels),
        'elements': elements,
        'isotopes': isotopes,
        'element_totals': element_totals,
        'isotope_totals': isotope_totals,
        'isotope_to_element': isotope_to_element,
    }


def calculate_element_counts_from_spectrum(
    element_spectrum_data: Dict,
    experimental_counts: np.ndarray,
    element_or_isotope: str,
    roi_start: int,
    roi_end: int,
    use_isotope: bool = False
) -> Tuple[int, float, float]:
    """
    Calculate element/isotope counts using simulation-guided weighting.
    
    This is the physically correct way to estimate A_A (element counts)
    for uncertainty calculation. It uses the simulated element spectrum
    to determine what fraction of the experimental counts belong to each element.
    
    Formula:
        f_A = Σ(sim_A[ROI]) / Σ(sim_total[ROI])
        A_A = Σ(exp[ROI]) × f_A
    
    Parameters
    ----------
    element_spectrum_data : dict
        Output from parse_element_spectrum()
    experimental_counts : np.ndarray
        Experimental spectrum from .xnra file
    element_or_isotope : str
        Element symbol (e.g., 'Si', 'O', 'Ca') or isotope (e.g., '12C', '16O')
    roi_start : int
        Start channel of ROI (inclusive)
    roi_end : int
        End channel of ROI (inclusive)
    use_isotope : bool, default=False
        If True, look for isotope-specific spectrum; if False, use element total
    
    Returns
    -------
    tuple
        (element_counts, element_fraction, total_exp_counts)
        - element_counts: Estimated counts for this element (A_A)
        - element_fraction: Fraction of ROI signal from this element (f_A)
        - total_exp_counts: Total experimental counts in ROI
    """
    # Get channel range from element spectrum
    channels = element_spectrum_data['channels']
    
    # Map ROI to array indices
    roi_mask = (channels >= roi_start) & (channels <= roi_end)
    
    if not np.any(roi_mask):
        return 0, 0.0, 0
    
    # Choose spectrum source based on whether we want isotope-specific data
    if use_isotope and element_or_isotope in element_spectrum_data.get('isotope_spectra', {}):
        sim_spectrum = element_spectrum_data['isotope_spectra'][element_or_isotope]
    elif element_or_isotope in element_spectrum_data.get('element_spectra', {}):
        sim_spectrum = element_spectrum_data['element_spectra'][element_or_isotope]
    else:
        # Try case-insensitive match
        for key, spectrum in element_spectrum_data.get('element_spectra', {}).items():
            if key.lower() == element_or_isotope.lower():
                sim_spectrum = spectrum
                break
        else:
            for key, spectrum in element_spectrum_data.get('isotope_spectra', {}).items():
                if key.lower() == element_or_isotope.lower():
                    sim_spectrum = spectrum
                    break
            else:
                return 0, 0.0, 0
    
    total_simulated = element_spectrum_data['total_simulated']
    
    # Sum in ROI
    sim_element_roi = np.sum(sim_spectrum[roi_mask])
    sim_total_roi = np.sum(total_simulated[roi_mask])
    
    # Element fraction
    if sim_total_roi > 0:
        element_fraction = sim_element_roi / sim_total_roi
    else:
        element_fraction = 0.0
    
    # Get experimental counts in ROI
    exp_roi_start = max(0, roi_start)
    exp_roi_end = min(len(experimental_counts), roi_end + 1)
    
    if exp_roi_start >= exp_roi_end:
        return 0, 0.0, 0
    
    total_exp_counts = int(np.sum(experimental_counts[exp_roi_start:exp_roi_end]))
    
    # Calculate element counts using simulation-guided weighting
    element_counts = int(total_exp_counts * element_fraction)
    
    return element_counts, element_fraction, total_exp_counts


# =============================================================================
# PLOTTING FUNCTION
# =============================================================================

def plot_element_spectra(element_spectrum_data: Dict,
                         elements_to_plot: List[str] = None,
                         isotopes_to_plot: List[str] = None,
                         show_total: bool = True,
                         figure_size: Tuple[float, float] = (12, 6),
                         dpi: int = 100,
                         title: str = None,
                         x_axis_mode: str = 'channel',
                         cal_offset: float = 0,
                         cal_gain: float = 1,
                         line_width: float = 1.5,
                         show_legend: bool = True,
                         show_plot: bool = True):
    """
    Plot element and/or isotope spectra from SIMNRA element spectrum file.
    
    Features interactive hover to identify elements/isotopes (requires mplcursors).
    
    Parameters
    ----------
    element_spectrum_data : dict
        Output from parse_element_spectrum()
    elements_to_plot : list, optional
        List of element symbols to plot. If None, plots all.
    isotopes_to_plot : list, optional
        List of isotope names to plot. If None and elements_to_plot is None, plots none.
    show_total : bool, default=True
        Show the total simulated spectrum as a black dashed line
    figure_size : tuple
        Figure size in inches
    dpi : int
        Figure resolution
    title : str, optional
        Plot title
    x_axis_mode : str
        'channel' or 'energy'
    cal_offset, cal_gain : float
        Energy calibration parameters (E = offset + gain × channel)
    line_width : float
        Line width for spectra
    show_legend : bool
        Show legend
    show_plot : bool
        Display the plot (call plt.show())
    
    Returns
    -------
    matplotlib.figure.Figure
        The figure object
    """
    import matplotlib.pyplot as plt
    
    channels = element_spectrum_data['channels']
    element_spectra = element_spectrum_data.get('element_spectra', {})
    isotope_spectra = element_spectrum_data.get('isotope_spectra', {})
    total_simulated = element_spectrum_data.get('total_simulated', None)
    
    # Determine what to plot
    if elements_to_plot is None and isotopes_to_plot is None:
        # Default: plot all elements
        elements_to_plot = element_spectrum_data.get('elements', [])
    
    if elements_to_plot is None:
        elements_to_plot = []
    if isotopes_to_plot is None:
        isotopes_to_plot = []
    
    # Create figure
    fig, ax = plt.subplots(figsize=figure_size, dpi=dpi)
    
    # X-axis values
    if x_axis_mode.lower() == 'energy':
        x_values = cal_offset + cal_gain * channels
        x_label = 'Energy [keV]'
    else:
        x_values = channels
        x_label = 'Channel'
    
    color_idx = 0
    lines = []  # Store line objects for hover
    line_labels = []  # Store corresponding labels
    
    # Plot total first (as background reference)
    if show_total and total_simulated is not None:
        line, = ax.plot(x_values, total_simulated, 
                color='black', linestyle='--', linewidth=line_width * 0.8,
                label='Total', alpha=0.5, zorder=1)
        lines.append(line)
        line_labels.append('Total (simulated)')
    
    # Plot elements
    for elem in elements_to_plot:
        if elem in element_spectra:
            color = ELEMENT_COLORS[color_idx % len(ELEMENT_COLORS)]
            line, = ax.plot(x_values, element_spectra[elem],
                    color=color, linewidth=line_width,
                    label=elem, zorder=2)
            lines.append(line)
            line_labels.append(elem)
            color_idx += 1
    
    # Plot isotopes
    for iso in isotopes_to_plot:
        if iso in isotope_spectra:
            color = ELEMENT_COLORS[color_idx % len(ELEMENT_COLORS)]
            line, = ax.plot(x_values, isotope_spectra[iso],
                    color=color, linewidth=line_width,
                    label=iso, linestyle='-.', zorder=2)
            lines.append(line)
            line_labels.append(iso)
            color_idx += 1
    
    # Labels and title
    ax.set_xlabel(x_label, fontsize=12, fontweight='bold')
    ax.set_ylabel('Counts', fontsize=12, fontweight='bold')
    
    if title:
        ax.set_title(title, fontsize=14, fontweight='bold')
    else:
        ax.set_title('Element Spectra', fontsize=14, fontweight='bold')
    
    # Legend
    if show_legend and (elements_to_plot or isotopes_to_plot or show_total):
        ax.legend(loc='upper right', fontsize=9, framealpha=0.9)
    
    # Grid
    ax.grid(True, alpha=0.3, linestyle='--')
    
    # ===== Interactive Hover using mplcursors =====
    try:
        import mplcursors
        
        # Create cursor for all lines
        # hover=2 makes annotation disappear immediately when not on a line
        cursor = mplcursors.cursor(lines, hover=2)
        
        @cursor.connect("add")
        def on_add(sel):
            """Customize the annotation when hovering"""
            line = sel.artist
            if line in lines:
                idx = lines.index(line)
                label = line_labels[idx]
                color = line.get_color()
                
                # Get position info
                x_val = sel.target[0]
                y_val = sel.target[1]
                
                # Build annotation text
                if label == 'Total (simulated)':
                    # Total spectrum: black, no color name
                    if x_axis_mode.lower() == 'energy':
                        text = f"Total\n{x_val:.1f} keV | {y_val:.0f} cts"
                    else:
                        text = f"Total\nCh {x_val:.0f} | {y_val:.0f} cts"
                    text_color = 'black'
                    border_color = 'black'
                else:
                    # Element/isotope: colored with color name
                    color_name = COLOR_NAMES.get(color, color)
                    if x_axis_mode.lower() == 'energy':
                        text = f"{label} ({color_name})\n{x_val:.1f} keV | {y_val:.0f} cts"
                    else:
                        text = f"{label} ({color_name})\nCh {x_val:.0f} | {y_val:.0f} cts"
                    text_color = color
                    border_color = color
                
                # Style the annotation
                sel.annotation.set_text(text)
                sel.annotation.set_fontsize(10)
                sel.annotation.set_fontweight('bold')
                sel.annotation.set_color(text_color)
                sel.annotation.get_bbox_patch().set_facecolor('white')
                sel.annotation.get_bbox_patch().set_alpha(0.95)
                sel.annotation.get_bbox_patch().set_edgecolor(border_color)
                sel.annotation.get_bbox_patch().set_linewidth(2)
        
        print("✓ Interactive hover enabled (mplcursors)")
        
    except ImportError:
        print("ℹ️  For interactive hover, install mplcursors: pip install mplcursors")
    
    plt.tight_layout()
    
    if show_plot:
        plt.show()
    
    return fig


# =============================================================================
# CLI / MAIN
# =============================================================================

def main():
    """Simple CLI for testing."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Plot SIMNRA element spectra')
    parser.add_argument('input', help='Element spectrum .txt file')
    parser.add_argument('-e', '--elements', help='Comma-separated elements to plot')
    parser.add_argument('-i', '--isotopes', help='Comma-separated isotopes to plot')
    parser.add_argument('--no-total', action='store_true', help='Hide total spectrum')
    parser.add_argument('--energy', action='store_true', help='Use energy x-axis')
    parser.add_argument('--offset', type=float, default=0, help='Calibration offset')
    parser.add_argument('--gain', type=float, default=1, help='Calibration gain')
    parser.add_argument('-t', '--title', help='Plot title')
    
    args = parser.parse_args()
    
    # Parse file
    data = parse_element_spectrum(args.input)
    summary = get_element_spectrum_summary(data)
    
    print(f"\nLoaded: {args.input}")
    print(f"Channels: {summary['channel_min']} - {summary['channel_max']} ({summary['n_channels']} points)")
    print(f"Elements: {', '.join(summary['elements'])}")
    print(f"Isotopes: {', '.join(summary['isotopes'])}")
    
    # Determine what to plot
    elements = None
    isotopes = None
    
    if args.elements:
        elements = [e.strip() for e in args.elements.split(',')]
    if args.isotopes:
        isotopes = [i.strip() for i in args.isotopes.split(',')]
    
    # Plot
    plot_element_spectra(
        data,
        elements_to_plot=elements,
        isotopes_to_plot=isotopes,
        show_total=not args.no_total,
        x_axis_mode='energy' if args.energy else 'channel',
        cal_offset=args.offset,
        cal_gain=args.gain,
        title=args.title,
    )


if __name__ == '__main__':
    main()
